version: '3'

services:
  repeat:
    image: ghcr.io/ravenholdt/chassitonrepeat:latest
    ports:
      - "8080:80"
    volumes:
      - "./files:/files"
      - "./config:/config"
    environment:
      MONGODB_URI: 'mongodb+srv://user:pass@url'
      ENABLE_PROXY: true
    restart: unless-stopped