name: Create and publish Docker image

on:
  push:
    tags:
      - 'v*'

jobs:
  build_docker:
    runs-on: ubuntu-latest
    name: Build docker image
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'

      - name: Setup Ko
        uses: ko-build/setup-ko@v0.6

      - name: Build and push
        run: ko build --tags latest --tags ${{ github.ref_name }}